public enum SpawnStringGamePlayingType
{
	MovableBoardEffect,
	BossCursorAppear,
	BossCursor,
	BossAttack,
	CrowMove,
	CrowBeAttacked,
	CrowRemove,
	MagicalCrowMove,
	MagicalCrowBeAttacked,
	MagicalCrowRemove,
	MagicalCrowAttack,
	MagicalCrowAttackedBlock,
	EffectDiggingCollect,
	EffectDiggingCollectTreasureG1,
	EffectDiggingCollectTreasureG2,
	EffectDiggingCollectTreasureG3,
	PocketCollect
}
